from celery import shared_task
import requests
import logging

logger = logging.getLogger(__name__)

@shared_task(name='auto_scrape_all_leagues')
def auto_scrape_all_leagues():
    """Scraping automatique de toutes les ligues (212 total)"""
    logger.info("=== DEBUT SCRAPING AUTOMATIQUE ===")

    leagues = [
        # FOOTBALL (105 compétitions)
        'football.a_league',
        'football.a_lyga',
        'football.a_pfg',
        'football.allsvenskan',
        'football.amical_international',
        'football.amical_international_w',
        'football.asian_champions_league',
        'football.bgl_ligue',
        'football.bov_premier_division',
        'football.brasileirao',
        'football.bundesliga',
        'football.bundesliga_2',
        'football.bundesliga_autriche',
        'football.casino_eredivisie',
        'football.champions_league',
        'football.championship',
        'football.club_world_cup',
        'football.community_shield',
        'football.concacaf_gold_cup',
        'football.concacaf_ligue_des_nations',
        'football.conference_league',
        'football.copa_libertadores',
        'football.copa_sudamericana',
        'football.coupe_asie',
        'football.coupe_d_asie',
        'football.coupe_d_italie',
        'football.coupe_de_france',
        'football.coupe_du_monde_des_clubs',
        'football.coupe_du_roi',
        'football.division_1_algerie',
        'football.division_1_chypre',
        'football.ekstraklasa',
        'football.eliteserien',
        'football.eredivisie',
        'football.erovnuli_liga',
        'football.euro_femmes',
        'football.euro_u21_qualif',
        'football.europa_league',
        'football.fa_cup',
        'football.het_liga',
        'football.hnl_1',
        'football.hnl_croatie',
        'football.j_league',
        'football.jupiler_pro_ligue',
        'football.k_league_1',
        'football.la_liga',
        'football.league_cup_efl',
        'football.league_of_wales',
        'football.leagues_cup',
        'football.liga_1_roumanie',
        'football.liga_2_cabovisao',
        'football.liga_2_portugal',
        'football.liga_adelante',
        'football.liga_mx',
        'football.liga_postobon',
        'football.liga_postobon_i',
        'football.ligue_1',
        'football.ligue_2',
        'football.ligue_des_champions_f',
        'football.ligue_des_nations',
        'football.ligue_des_nations_f',
        'football.ligue_europa',
        'football.ligue_nations_f',
        'football.major_league_soccer',
        'football.meistriliiga',
        'football.mls',
        'football.nb_i_hongrie',
        'football.orange_ekstraklasa',
        'football.pokal_cup',
        'football.premier_division_irlande',
        'football.premier_league',
        'football.premier_liga_bosnie',
        'football.premier_liga_ukraine',
        'football.premiere_division_azerbaidjan',
        'football.premiership_ecosse',
        'football.premiership_irlande_du_nord',
        'football.primeira_liga',
        'football.primera_division_argentine',
        'football.primera_division_chili',
        'football.primera_division_paraguay',
        'football.prvaliga',
        'football.qualif_wc_afrique',
        'football.qualif_wc_amerique_du_sud',
        'football.qualif_wc_asie',
        'football.qualif_wc_concacaf',
        'football.qualif_wc_europe',
        'football.qualif_world_cup_south_america',
        'football.saudi_pro_league',
        'football.serie_a',
        'football.serie_a_equateur',
        'football.serie_b',
        'football.super_league_chine',
        'football.super_league_grece',
        'football.super_league_maroc',
        'football.super_league_serbie',
        'football.super_league_suisse',
        'football.super_ligi',
        'football.superliga_slovaquie',
        'football.superligaen',
        'football.ucl_femmes',
        'football.uefa_conference_league',
        'football.urvalsdeild',
        'football.veikkausliiga',
        'football.virsliga',
        'football.winner_league',

        # TENNIS (89 tournois)
        'tennis.atp_almaty',
        'tennis.atp_athens',
        'tennis.atp_barcelone',
        'tennis.atp_basel',
        'tennis.atp_bastad',
        'tennis.atp_bruxelles',
        'tennis.atp_bucharest',
        'tennis.atp_chengdu',
        'tennis.atp_cincinnati',
        'tennis.atp_eastbourne',
        'tennis.atp_geneve',
        'tennis.atp_gstaad',
        'tennis.atp_halle',
        'tennis.atp_hambourg',
        'tennis.atp_hangzhou',
        'tennis.atp_hertogenbosch',
        'tennis.atp_houston',
        'tennis.atp_kitzbuhel',
        'tennis.atp_london',
        'tennis.atp_los_cabos',
        'tennis.atp_madrid',
        'tennis.atp_majorque',
        'tennis.atp_marrakech',
        'tennis.atp_miami',
        'tennis.atp_monte_carlo',
        'tennis.atp_munich',
        'tennis.atp_paris',
        'tennis.atp_pekin',
        'tennis.atp_rome',
        'tennis.atp_shanghai',
        'tennis.atp_stockholm',
        'tennis.atp_stuttgart',
        'tennis.atp_tokyo',
        'tennis.atp_toronto',
        'tennis.atp_umag',
        'tennis.atp_us_open',
        'tennis.atp_us_open_double',
        'tennis.atp_vienne',
        'tennis.atp_washington',
        'tennis.atp_wimbledon',
        'tennis.atp_winston_salem',
        'tennis.coupe_davis',
        'tennis.roland_garros_doubles_m',
        'tennis.roland_garros_doubles_w',
        'tennis.roland_garros_doubles_x',
        'tennis.roland_garros_m',
        'tennis.roland_garros_w',
        'tennis.wimbledon_double_m',
        'tennis.wimbledon_double_w',
        'tennis.wimbledon_double_x',
        'tennis.wta_bad_homburg',
        'tennis.wta_berlin',
        'tennis.wta_bogota',
        'tennis.wta_charleston',
        'tennis.wta_chennai',
        'tennis.wta_cincinnati',
        'tennis.wta_cleveland',
        'tennis.wta_eastbourne',
        'tennis.wta_finals_riyadh',
        'tennis.wta_guadalajara',
        'tennis.wta_guangzhou',
        'tennis.wta_hamburg',
        'tennis.wta_hertogenbosch',
        'tennis.wta_hong_kong',
        'tennis.wta_iasi',
        'tennis.wta_jiujiang',
        'tennis.wta_londres',
        'tennis.wta_madrid',
        'tennis.wta_miami',
        'tennis.wta_monterrey',
        'tennis.wta_montreal',
        'tennis.wta_ningbo',
        'tennis.wta_nottingham',
        'tennis.wta_osaka',
        'tennis.wta_pekin',
        'tennis.wta_prague',
        'tennis.wta_rabat',
        'tennis.wta_rome',
        'tennis.wta_rouen',
        'tennis.wta_sao_paulo',
        'tennis.wta_seoul',
        'tennis.wta_strasbourg',
        'tennis.wta_stuttgart',
        'tennis.wta_tokyo',
        'tennis.wta_us_open',
        'tennis.wta_us_open_double',
        'tennis.wta_washington',
        'tennis.wta_wimbledon',
        'tennis.wta_wuhan',

        # BASKETBALL (15 ligues)
        'basketball.a1',
        'basketball.betclic_elite',
        'basketball.bundesliga',
        'basketball.coupe_d_europe_fiba',
        'basketball.euro_league',
        'basketball.eurocup',
        'basketball.eurocup_women',
        'basketball.euroligue',
        'basketball.euroligue_women',
        'basketball.league_aba',
        'basketball.lega_a',
        'basketball.ligue_des_champions',
        'basketball.nba',
        'basketball.nbl',
        'basketball.serie_a2',

        # RUGBY (3 compétitions)
        'rugby.pro_d2',
        'rugby.test_match',
        'rugby.top_14',
    ]
    
    results = []
    for league in leagues:
        try:
            logger.info(f"Scraping: {league}")
            
            # Appel à l'API de scraping Django
            response = requests.post(
                'http://backend:8000/api/scraping/trigger',
                json={'scraper': league},
                timeout=600
            )
            
            success = response.status_code == 200
            results.append({
                'league': league,
                'success': success,
                'status_code': response.status_code
            })
            
            logger.info(f"{league}: {'OK' if success else 'ERREUR'} (status={response.status_code})")
            
        except requests.exceptions.Timeout:
            logger.error(f"{league}: TIMEOUT")
            results.append({'league': league, 'success': False, 'error': 'timeout'})
        except Exception as e:
            logger.error(f"{league}: {str(e)}")
            results.append({'league': league, 'success': False, 'error': str(e)})
    
    success_count = sum(1 for r in results if r.get('success'))
    logger.info(f"=== FIN: {success_count}/{len(results)} succes ===")
    
    return results
